### ISSUE TITLE
Command line version?

### ISSUE THREAD

**Issue by SziKayLeung** [helmercitterich-lab/BRIO#14]
Hello, 

Thank you for developing BRIO - the BRIO website is really useful and intuitive. 

However, I was wondering if there's a command line or an option to run more than 100 sequences at a time (my dataset has over 2000 sequences...)?

I was also wondering what was the rationale for input RNA molecules to be less than 3000 nucleotides long, given that some mRNA sequences can be >10kb long?

Thank you,
Szi Kay

**Comment by AndreaGuarracino** [comment]
Hi @SziKayLeung,
I've just pushed a dumb [notebook](https://github.com/bioinformatics-torvergata/BRIO/blob/master/notebooks/launch_BRIO.ipynb) I've written some time ago to directly launch BRIO's core functionality locally. I hope this can help in guiding you in writing your scripts.

The limitations in RNA lengths are due to computational reasons and the predictions of secondary structures that become more inaccurate with increasing length. Locally, you can avoid this length constraint and work with any length.
